name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number and name
      run: printf '{\n  "domain": "entities_calendar",\n  "name": "Entities Calendar",\n  "documentation": "https://github.com/gadgetchnnel/entities_calendar/",\n  "issue_tracker": "https://github.com/gadgetchnnel/entities_calendar/issues",\n  "codeowners": ["@gadgetchnnel"]\n  "version": "${{ github.event.inputs.versionCode }}"\n}' > custom_components/entities_calendar/manifest.json
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add custom_components/entities_calendar/manifest.json
        git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request into master
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: master
       title: v${{ github.event.inputs.versionName }} into master
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
